### ISSUE TITLE
checklist for repo

### ISSUE THREAD

**Issue by younes8888** [HYF-Class22/group1-hyf-rebuild#2]
- [x] [repo](https://github.com/HYF-Class22/group1-hyf-rebuild) (with a complete README)
- [x] [live demo](https://hyf-class22.github.io/group1-hyf-rebuild/)
- [x] We used only plain CSS
- [/planning](https://github.com/_/_/tree/main/planning)
  - [x] communication plan
  - [x] constraints
  - [x] backlog
  - [x] wireframe
  - [x] development strategy
  - [x] retrospective
- [x] [project board](https://github.com/_/_/projects/1)
